package com.tsengine.common;

/**
 * Represents the source used to generate commentary text.
 */
public enum CommentaryGenerationType {
    AI("Generated by Claude AI"),
    TEMPLATE("Generated by deterministic template fallback");

    private final String description;

    CommentaryGenerationType(String description) {
        this.description = description;
    }

    /**
     * Returns the human-readable generation source description.
     *
     * @return generation source description
     */
    public String getDescription() {
        return description;
    }
}
